#!/bin/bash

set -e

[ -z "$LIBEXECDIR" ] && LIBEXECDIR="/usr/libexec"
[ -z "$DATADIR" ] && DATADIR="/usr/share"
[ -z "$LIB" ] && $(echo nash-showelfinterp /usr/bin/plymouth | /sbin/nash --forcequiet | grep -q lib64) && LIB="lib64" || LIB="lib"
[ -z "$LIBDIR" ] && LIBDIR="/usr/$LIB"
[ -z "$BINDIR" ] && BINDIR="/usr/bin"

if [ $# -lt 1 ]; then
        PLUGIN_NAME=$(basename $(readlink ${LIBDIR}/plymouth/default.so) .so)
        if [ -z "$PLUGIN_NAME" ]; then
                $0 --reset
                PLUGIN_NAME=$(basename $(readlink ${LIBDIR}/plymouth/default.so) .so)
        fi
        [ -n "$PLUGIN_NAME" ] && echo $PLUGIN_NAME || exit 1
        exit $?
fi

if [ `id -u` -ne 0 ]; then
        echo "This program must be run as root" > /dev/stderr
        exit 1
fi

PLUGIN_NAME=$1
if [ $1 = '--reset' ]; then
        PLUGIN_NAME=$(basename $(ls -1 -t ${LIBDIR}/plymouth/*.so 2> /dev/null | grep -v default.so | tail -n 1) .so)
        if [ $PLUGIN_NAME = .so ]; then
                rm -f ${LIBDIR}/plymouth/default.so
                exit 0
        fi
fi

if [ ! -e ${LIBDIR}/plymouth/${PLUGIN_NAME}.so ]; then
        echo "${LIBDIR}/plymouth/${PLUGIN_NAME}.so does not exist" > /dev/stderr
        exit 1
fi

(cd ${LIBDIR}/plymouth; ln -sf ${PLUGIN_NAME}.so default.so)

